### PR TITLE
allow user to skip TLS

### PR DESCRIPTION
**Pull request by pradeepbbl**
Set `SkipTLS` option

### CODE REVIEW

**Comment by pradeepbbl** [comment]
Test result (with skip_ssl set to true)
==================== =======
```shell

root@httpbin-ff5c59f7c-sb2l7:~/test_ectd# cat version.tf 
# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform { 
  required_version = ">= 1.4.0"
  required_providers {
    etcd  = {
      source = "Ferlab-Ste-Justine/etcd"
    }
  }
}

root@httpbin-ff5c59f7c-sb2l7:~/test_ectd# cat provider.tf 
provider "etcd" {
  skip_tls = true
}
root@httpbin-ff5c59f7c-sb2l7:~/test_ectd# terraform apply -var-file tt.var 
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - ferlab-ste-justine/etcd in /root/test_ectd/terraform-provider-etcd
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # etcd_role.roles["test"] will be created
  + resource "etcd_role" "roles" {
      + id   = (known after apply)
      + name = "test"

      + permissions {
          + key        = "/test"
          + permission = "readwrite"
          + range_end  = "/test/"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

etcd_role.roles["test"]: Creating...
etcd_role.roles["test"]: Creation complete after 0s [id=test]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
root@httpbin-ff5c59f7c-sb2l7:~/test_ectd# etcdctl  role list 
2023-07-14 00:38:54.407251 W | pkg/flags: unrecognized environment variable ETCDCTL_USERNAME=root
test
```

**Comment by pradeepbbl** [comment]
this will help access the cluster running behind `istio` service mess with `mTLS`  enabled.
Screenshot 2023-07-14 at 02 47 35

**Comment by Magnitus-** [comment]
While I don't think we'll have a use case for this in the foreseeable future, it is indeed a simple adjustment for those wishing to do tls termination on both ends like you are doing with a service mesh/proxy or wish to manage etcd in plaintext within a trusted network (possibly locally without dealing with tls).

I did some validation and it works. I'll add it to the local validation code, do some documentation update and release it. Thanks for your contribution.

**Comment by pradeepbbl** [comment]
Thanks for considering this PR +100

**Pull request merged**
