### PR TITLE
feat: Allow configure auth

### PR DESCRIPTION
**Pull request by paragor**

### CODE REVIEW

**Comment by paragor** [comment]
require https://github.com/Ferlab-Ste-Justine/etcd-sdk/pull/2

**Comment by Magnitus-** [comment]
@paragor I updated the project with the latest etcd sdk.

Some feedback:
- In the example code, I believe the property should be "enabled" and not "enable"
- For the description of the resource, perhaps this: "Controls the authentication status (enabled or disabled) of the etcd cluster."
- The call to the etcd sdk will have to be adjusted with the name changes of the auth methods
- For the id value, even though it is a constant given the singleton nature of the resource, I'd set it to "auth" rather than "none"

Looks good to me otherwise.

**Comment by paragor** [comment]
> @paragor I updated the project with the latest etcd sdk.
> 
> Some feedback:
> 
> * In the example code, I believe the property should be "enabled" and not "enable"
> * For the description of the resource, perhaps this: "Controls the authentication status (enabled or disabled) of the etcd cluster."
> * The call to the etcd sdk will have to be adjusted with the name changes of the auth methods
> * For the id value, even though it is a constant given the singleton nature of the resource, I'd set it to "auth" rather than "none"
> 
> Looks good to me otherwise.

Thank you, all done.

**Review by Magnitus- — APPROVED** [review]
Thanks for your contribution. I'll do a quick round of validation and then a release.

**Pull request merged**
